"""Model-authored deliverables: ```cmn:file``` fences become downloadable files.

The system prompt teaches models to wrap a requested document's full content in a
fenced block ```cmn:file name="bericht.pdf" … ```. This module extracts those blocks
from an answer (replacing them with a short German placeholder), infers the target
format from the file name, and keeps the generated bytes in a small in-memory store
with a TTL so /api/files/{id} can serve them. Restart loses the files by design —
the answer text survives in the conversation and the manual export buttons can
regenerate any document.
"""

from __future__ import annotations

import re
import time
import uuid
from collections.abc import Callable
from dataclasses import dataclass
from typing import Protocol, runtime_checkable

_FENCE = re.compile(
    r'```cmn:file[ \t]+name="([^"\n]+)"(?:[ \t]+theme="([^"\n]*)")?[ \t]*\n(.*?)```[ \t]*\n?',
    re.DOTALL,
)

_MEDIA_TYPES = {
    "pdf": "application/pdf",
    "pptx": "application/vnd.openxmlformats-officedocument.presentationml.presentation",
    "docx": "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    "md": "text/markdown",
}

_TTL_SECONDS = 3600.0
_MAX_TOTAL_BYTES = 50 * 1024 * 1024


@dataclass(frozen=True)
class Deliverable:
    """One file the model asked us to produce."""

    name: str
    format: str  # "pdf" | "pptx" | "docx" | "md"
    content: str  # the markdown source of the document
    theme: str = ""  # optional visual theme (report | modern | elegant | deck); "" = default

    @property
    def media_type(self) -> str:
        return _MEDIA_TYPES[self.format]


def _format_for(name: str) -> str:
    dot = name.rfind(".")
    ext = name[dot + 1 :].lower() if dot != -1 else ""
    return ext if ext in ("pdf", "pptx", "docx") else "md"


def extract_deliverables(text: str) -> tuple[str, list[Deliverable]]:
    """Split an answer into clean prose and the deliverables it embeds.

    Malformed markers are left verbatim — never destroy model output.
    """
    files: list[Deliverable] = []

    def _replace(m: re.Match[str]) -> str:
        name = m.group(1).strip()
        theme = (m.group(2) or "").strip()
        files.append(
            Deliverable(
                name=name, format=_format_for(name), content=m.group(3).strip(), theme=theme
            )
        )
        return f"„{name}“ wurde erstellt (siehe Download).\n"

    clean = _FENCE.sub(_replace, text)
    return clean, files


@dataclass
class StoredFile:
    name: str
    media_type: str
    data: bytes
    created_at: float


@runtime_checkable
class FileBackend(Protocol):
    """Interface both the in-memory and Supabase file stores satisfy."""

    def put(self, name: str, media_type: str, data: bytes) -> str: ...
    def get(self, file_id: str) -> StoredFile | None: ...


class FileStore:
    """Tiny in-memory store for generated files (uuid ids, TTL, size-capped)."""

    def __init__(
        self,
        *,
        now: Callable[[], float] = time.monotonic,
        ttl_seconds: float = _TTL_SECONDS,
        max_total_bytes: int = _MAX_TOTAL_BYTES,
    ) -> None:
        self._files: dict[str, StoredFile] = {}
        self._now = now
        self._ttl = ttl_seconds
        self._cap = max_total_bytes

    def _purge_expired(self) -> None:
        now = self._now()
        for fid in [f for f, item in self._files.items() if now - item.created_at > self._ttl]:
            del self._files[fid]

    def put(self, name: str, media_type: str, data: bytes) -> str:
        self._purge_expired()

        # Evict oldest (insertion order) until the new file fits.
        def _total() -> int:
            return sum(len(f.data) for f in self._files.values())

        while self._files and _total() + len(data) > self._cap:
            del self._files[next(iter(self._files))]
        fid = uuid.uuid4().hex
        self._files[fid] = StoredFile(
            name=name, media_type=media_type, data=data, created_at=self._now()
        )
        return fid

    def get(self, file_id: str) -> StoredFile | None:
        self._purge_expired()
        return self._files.get(file_id)
